file = [ws], { element }, [ws] ;
element = nest_element | text_element | empty_element ;
nest_element = open_tag, [ws], element_array, [ws], close_tag ;
text_element = open_tag, text, close ;
empty_element = open_close_tag ;
element_array = element, { [ws], element } ;
open_tag = "{{", [ws], word, { ws, property }, [ws], "}}" ;
close_tag = "{{", [ws], "/", [ws], word, [ws], "}}" ;
open_close_tag = "{{", [ws], word, { ws property }, [ws], "/", [ws], "}}" ;
property = word, [ws], "=", [ws], property_value ;
property_value = unquoted_property_value | quoted_property_value ;
unquoted_property_value = word ;
quoted_property_value = "\"", quoted_text, "\"" ;
text = { text_token } ;
text_token = "\"" | "/" | "=" | word | ws_token ;
quoted_text = { quoted_text_token } ;
quoted_text_token = "{{" | "}}" | "/" | "=" | word | ws_token ;
ws = ws_token, { ws_token } ;
ws_token = "\s" | "\t" | "\n" ;
word = word_token, { word_token } ;
word_token = ? all nonspecial characters (excluding whitespace too) ? ;
